version: '2'

services:
  server:
    image: aerokube/selenoid:latest
    ports:
    - 4444:4444
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${PWD}/video:/opt/selenoid/video
    - ${PWD}/config:/etc/selenoid
    command: ['-limit', '10', '-service-startup-timeout', '2m', '-session-attempt-timeout', '2m', '-session-delete-timeout', '2m']
    network_mode: bridge
    environment:
      OVERRIDE_VIDEO_OUTPUT_DIR: ${PWD}/video
